### ISSUE TITLE
关于加入SPP提取多尺寸特征但loss不下降的问题咨询

### ISSUE THREAD

**Issue by brotherNanNan** [suhangpro/mvcnn#10]

**Comment by suhangpro** [comment]
@brotherNanNan Sorry for the slow response. I don't have experience with SPP so won't be able to provide any insights on this. Please consider sharing your findings with us here if you figured out a solution. Thanks!

**Comment by brotherNanNan** [comment]
@suhangpro I have given up this attemp, the loss just doesn't decline..
