### ISSUE TITLE
precious

### ISSUE THREAD

**Issue by mjchen611** [suhangpro/mvcnn#11]
The program runs to modelnet experimental phase 2-mvcnn,net’s viewpool layer not have the field of ‘precious’.Can you give me some advice?Thank you

**Comment by suhangpro** [comment]
This seems like a problem caused by incompatible matconvnet version. Are you using the version provided in the "dependencies" folder?

**Comment by mjchen611** [comment]
I download the master version,in the "Dependencies" folder, the subfolder "matconvnet" folder is empty,I download the matconvnet-1.0-beta24 version,can you give me some advice?

**Comment by mjchen611** [comment]
I have solved the problem,it is really caused by incompatible matconvnet version.Thank you very  much!
