### ISSUE TITLE
Hardware requirement for training

### ISSUE THREAD

**Issue by nguyenminhduc9988** [suhangpro/mvcnn#2]
I have a 2GB card but the program always exit with out of memory on GPU. I was wondering how much RAM does it take to do training.

**Comment by suhangpro** [comment]
6GB is the minimum. You might be able to reduce the requirement by using smaller batch sizes.

**Comment by nguyenminhduc9988** [comment]
Thank you for the answer, I switch to using cpu because my card does not have enough memory.
