### ISSUE TITLE
What's the meaning of 'relative magnitude of gradient energy' ?

### ISSUE THREAD

**Issue by JL-Cheng** [suhangpro/mvcnn#28]
You mentioned the concept **'relative magnitude of gradient energy'** in section 4.1. However, I don't know the meaning of it and thus don't know how to calculate it from the saliency map.
![image](https://user-images.githubusercontent.com/30789532/76746371-5d935e00-67b2-11ea-918c-ea7cef2d7c0c.png)

**Comment by suhangpro** [comment]
relative magnitude here simply means rescaling each map separately so that the values in each view is within [0,1].

**Comment by JL-Cheng** [comment]
Ok, I know that. But after rescaling each saliency map, I get tensors of size (224,224). However, I see that there is a floating point value for each view, such as **0.45**, **0.85**, **1.15** in Figure 3, and I don't know the meaning of these values.

**Comment by suhangpro** [comment]
Those are the mean magnitude of each map (before rescaling) -- so only comparing the numbers within the same rows would make sense.

**Comment by JL-Cheng** [comment]
Ok, I get it, thank you.
