### ISSUE TITLE
Issue with compiling on GPU

### ISSUE THREAD

**Issue by xiao1228** [suhangpro/mvcnn#3]
Hi,
I ran to an issue when I use 
`matlab -nodisplay -r "setup(true,struct('enableGpu',true,'enableCudnn',true));exit;"`
The errors I got are 

> Building with 'nvcc'.
> Error using mex
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(112): error: argument of
> type "int" is incompatible with parameter of type "cudnnTensorFormat_t"
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::forward(vl::Context &,
>           vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with
>           dataType=vl::vlTypeFloat]"
> (537): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(112): error: too few
> arguments in function call
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::forward(vl::Context &,
>           vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with
>           dataType=vl::vlTypeFloat]"
> (537): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(312): error: argument of
> type "ptrdiff_t" is incompatible with parameter of type "cudnnTensorFormat_t"
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &,
>           vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int)
>           [with dataType=vl::vlTypeFloat]"
> (537): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(312): error: too few
> arguments in function call
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &,
>           vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int)
>           [with dataType=vl::vlTypeFloat]"
> (537): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(339): error: argument of
> type "ptrdiff_t" is incompatible with parameter of type "cudnnTensorFormat_t"
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &,
>           vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int)
>           [with dataType=vl::vlTypeFloat]"
> (537): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(339): error: too few
> arguments in function call
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &,
>           vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int)
>           [with dataType=vl::vlTypeFloat]"
> (537): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(112): error: argument of
> type "int" is incompatible with parameter of type "cudnnTensorFormat_t"
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::forward(vl::Context &,
>           vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with
>           dataType=vl::vlTypeDouble]"
> (540): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(112): error: too few
> arguments in function call
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::forward(vl::Context &,
>           vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with
>           dataType=vl::vlTypeDouble]"
> (540): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(312): error: argument of
> type "ptrdiff_t" is incompatible with parameter of type "cudnnTensorFormat_t"
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &,
>           vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int)
>           [with dataType=vl::vlTypeDouble]"
> (540): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(312): error: too few
> arguments in function call
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &,
>           vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int)
>           [with dataType=vl::vlTypeDouble]"
> (540): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(339): error: argument of
> type "ptrdiff_t" is incompatible with parameter of type "cudnnTensorFormat_t"
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &,
>           vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int)
>           [with dataType=vl::vlTypeDouble]"
> (540): here
> /home/xiao/Documents/mvcnn/dependencies/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(339): error: too few
> arguments in function call
>           detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &,
>           vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int)
>           [with dataType=vl::vlTypeDouble]"
> (540): here
> 12 errors detected in the compilation of "/tmp/tmpxft_00007998_00000000-7_nnconv_cudnn.cpp1.ii".
> 
> Error in vl_compilenn>mex_compile (line 478)
> mex(mopts{:}) ;
> 
> Error in vl_compilenn (line 436)
>       mex_compile(opts, srcs{i}, objfile, flags.mexcu) ;
> 
> Error in setup (line 67)
>     vl_compilenn(matconvnetOpts);
> 
> I am using cudnn 5.1 will this be the issue??

**Comment by suhangpro** [comment]
It should be the problem of incompatible cudnn version. This repo is build on top of a modified version of MatConvNet 1.0-beta18, but MatConvNet started to support cudnn 5 in 1.0-beta19.

**Comment by xiao1228** [comment]
Hi @suhangpro 
Thank you, i will go for the CPU version for now then.

**Comment by ghost** [comment]
I have similar errors when I run - matlab -nodisplay -r "setup(true,struct('enableGpu',true,'cudaRoot', '/usr/local/cuda-8.0', 'cudaMethod', 'nvcc','enableCudnn', true,'cudnnRoot', '/usr/local/cuda-8.0/include/'));exit;" on Ubuntu, CUDA-8 and CUDNN 5. 
Do I have to downgrade to CUDNN 4 to make it work?
Thank you!
