### ISSUE TITLE
Reference to non-existent field 'learningRate'.

### ISSUE THREAD

**Issue by HTLife** [suhangpro/mvcnn#5]
In iccv branch, after I execute 
`matlab -nodisplay -r "run_experiments;exit;"`
The following error message prompt out.  How should I do to fix this problem?

```
  [36/40] toilet ... 	train/val/test: 64/16/20 (shapes)
  [37/40] tv_stand ... 	train/val/test: 64/16/20 (shapes)
  [38/40] vase ... 	train/val/test: 64/16/20 (shapes)
  [39/40] wardrobe ... 	train/val/test: 64/16/20 (shapes)
  [40/40] xbox ... 	train/val/test: 64/16/20 (shapes)
Loading imdb from data/modelnet40v1/imdb.mat ... done!
Downloading model (imagenet-matconvnet-vgg-m) ... done!
Reference to non-existent field 'learningRate'.

Error in cnn_shape>@(l)l.learningRate (line 129)
lr = cellfun(@(l) l.learningRate, net.layers(trainable_layers),'UniformOutput',false);

Error in cnn_shape (line 129)
lr = cellfun(@(l) l.learningRate, net.layers(trainable_layers),'UniformOutput',false);

Error in run_experiments (line 12)
cnn_shape('modelnet40v1', ...
 
>> 
```

**Comment by jerryjliu** [comment]
^^ Bump, I want to second this. I'm not sure I understand the purpose of this code. I tried digging into the code and commenting out `lr = cellfun(@(l) l.learningRate, net.layers(trainable_layers),'UniformOutput',false);` as well as `net.layers{l}.learningRate = lr{i};` and `net.layers{l}.learningRate = lr{i}*0;`, assuming the training function would set a default learning rate, but then the objective function explodes and I get "NaN's." 

Is this a bug with the code?

**Comment by suhangpro** [comment]
@jerryjliu Are you also seeing this problem with the iccv branch? It might be a compatibility problem with current version of pre-trained models.

**Comment by jerryjliu** [comment]
@suhangpro This is with the master branch - should I switch to the iccv branch?

**Comment by suhangpro** [comment]
The master branch pulls a pre-trained model from matconvnet server, which might have recently updated the format of their models. Try using this model: http://maxwell.cs.umass.edu/mvcnn-data/models/imagenet-matconvnet-vgg-m.mat

**Comment by jerryjliu** [comment]
@suhangpro Thanks for your help. I think this error should be resolved. I'm now getting the error `Error using vl_nnconv` and `An input is not a numeric array (or GPU support not compiled).` even though I'm compiling on CPU, but can discuss that issue in a separate thread.

**Comment by priyam1994** [comment]
@suhangpro  I downloaded and used the model from your suggested link and got the following output/errors after I execute **matlab -nodisplay -r "run_experiments;exit;"** 
How do I fix this?

Loading imdb from data/modelnet40v1/imdb.mat ... done!
     layer|    0|    1|    2|    3|    4|    5|      6|    7|    8|    9|   10|   11|   12|   13|   14|   15|   16|   17|
      type|input| conv| relu|mpool| conv| relu|  mpool| conv| relu| conv| relu| conv| relu|mpool| conv| relu| conv| relu|
      name|  n/a|conv1|relu1|pool1|conv2|relu2|  pool2|conv3|relu3|conv4|relu4|conv5|relu5|pool5|  fc6|relu6|  fc7|relu7|
----------|-----|-----|-----|-----|-----|-----|-------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
   support|  n/a|    7|    1|    3|    5|    1|      3|    3|    1|    3|    1|    3|    1|    3|    6|    1|    1|    1|
  filt dim|  n/a|    3|  n/a|  n/a|   96|  n/a|    n/a|  256|  n/a|  512|  n/a|  512|  n/a|  n/a|  512|  n/a| 4096|  n/a|
 num filts|  n/a|   96|  n/a|  n/a|  256|  n/a|    n/a|  512|  n/a|  512|  n/a|  512|  n/a|  n/a| 4096|  n/a| 4096|  n/a|
    stride|  n/a|    2|    1|    2|    2|    1|      2|    1|    1|    1|    1|    1|    1|    2|    1|    1|    1|    1|
       pad|  n/a|    0|    0|    0|    1|    0|0x1x0x1|    1|    0|    1|    0|    1|    0|    0|    0|    0|    0|    0|
----------|-----|-----|-----|-----|-----|-----|-------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
   rf size|  n/a|    7|    7|   11|   27|   27|     43|   75|   75|  107|  107|  139|  139|  171|  331|  331|  331|  331|
 rf offset|  n/a|    4|    4|    6|   10|   10|     18|   18|   18|   18|   18|   18|   18|   34|  114|  114|  114|  114|
 rf stride|  n/a|    2|    2|    4|    8|    8|     16|   16|   16|   16|   16|   16|   16|   32|   32|   32|   32|   32|
----------|-----|-----|-----|-----|-----|-----|-------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
 data size|  224|  109|  109|   54|   26|   26|     13|   13|   13|   13|   13|   13|   13|    6|    1|    1|    1|    1|
data depth|    3|   96|   96|   96|  256|  256|    256|  512|  512|  512|  512|  512|  512|  512| 4096| 4096| 4096| 4096|
  data num|   60|   60|   60|   60|   60|   60|     60|   60|   60|   60|   60|   60|   60|   60|   60|   60|   60|   60|
----------|-----|-----|-----|-----|-----|-----|-------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
  data mem| 34MB|261MB|261MB| 64MB| 40MB| 40MB|   10MB| 20MB| 20MB| 20MB| 20MB| 20MB| 20MB|  4MB|960KB|960KB|960KB|960KB|
 param mem|  n/a| 56KB|   0B|   0B|  2MB|   0B|     0B|  5MB|   0B|  9MB|   0B|  9MB|   0B|   0B|288MB|   0B| 64MB|   0B|

     layer|   18|     19|
      type| conv|softmxl|
      name|  fc8|   loss|
----------|-----|-------|
   support|    1|      1|
  filt dim| 4096|    n/a|
 num filts|   40|    n/a|
    stride|    1|      1|
       pad|    0|      0|
----------|-----|-------|
   rf size|  331|    331|
 rf offset|  114|    114|
 rf stride|   32|     32|
----------|-----|-------|
 data size|    1|      1|
data depth|   40|      1|
  data num|   60|      1|
----------|-----|-------|
  data mem|  9KB|     4B|
 param mem|640KB|     0B|

parameter memory|378MB (9.9e+07 parameters)|
     data memory| 837MB (for batch size 60)|


ans = 

  CUDADevice with properties:

                      Name: 'GeForce 920M'
                     Index: 1
         ComputeCapability: '3.5'
            SupportsDouble: 1
             DriverVersion: 8
            ToolkitVersion: 8
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 2.1015e+09
           AvailableMemory: 1.6750e+09
       MultiprocessorCount: 2
              ClockRateKHz: 954000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

train: epoch 01:   1/510: Invalid MEX-file '/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64':
Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4dataEv' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4sizeEv' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6lengthEv' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKc' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKcm' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendERKS4_' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSERKS4_' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4_' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLERKS4_' required by
'/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'GOMP_critical_end' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'GOMP_critical_start' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'GOMP_loop_dynamic_next' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'GOMP_loop_dynamic_start' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'GOMP_loop_end_nowait' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'GOMP_parallel_end' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'GOMP_parallel_start' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'omp_get_max_threads' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'omp_get_num_threads' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol 'omp_get_thread_num' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libcusolver.so.8.0->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpucompiler.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__cxa_allocate_exception' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__cxa_begin_catch' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__cxa_end_catch' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__cxa_guard_acquire' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__cxa_guard_release' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__cxa_pure_virtual' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__cxa_rethrow' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__cxa_throw' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '__gxx_personality_v0' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZdaPv' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZdlPv' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_Znam' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZNSt9exceptionD1Ev' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_Znwm' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZSt17__throw_bad_allocv' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZSt20__throw_length_errorPKc' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZTISt9exception' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZTVN10__cxxabiv117__class_type_infoE' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZTVN10__cxxabiv120__si_class_type_infoE' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'
Missing symbol '_ZTVSt9exception' required by
'/usr/local/MATLAB/R2017a/bin/glnxa64/libmwmagma.so->/usr/local/MATLAB/R2017a/bin/glnxa64/libmwgpu.so->/home/vibha/Thesis/workspace/mvcnn/dependencies/matconvnet/matlab/mex/vl_imreadjpeg.mexa64'.

Error in cnn_shape_get_batch (line 45)
    im = vl_imreadjpeg(images,'numThreads', opts.numThreads) ;

Error in cnn_shape>getSimpleNNBatch (line 195)
  im = cnn_shape_get_batch(images, opts, ...

Error in cnn_shape>@(x,y)getSimpleNNBatch(bopts,x,y) (line 177)
    fn = @(x,y) getSimpleNNBatch(bopts,x,y) ;

Error in cnn_shape_train>process_epoch (line 309)
    [im, labels] = getBatch(imdb, batch) ;

Error in cnn_shape_train (line 148)
    [net,stats.train,prof] = process_epoch(opts, getBatch, epoch, train, learningRate, imdb, net) ;

Error in cnn_shape (line 141)
  net = trainFn(net, imdb, getBatchFn(opts, net.meta), ...

Error in run_experiments (line 12)
cnn_shape('modelnet40v1', ...
