### ISSUE TITLE
关于caffe imp的问题

### ISSUE THREAD

**Issue by brotherNanNan** [suhangpro/mvcnn#7]
您好，我在运行caffe imp的时候，出现了一个问题，在加载完预训练model后，开始训练的时候 python奔溃，我在windows及ubuntu下都试了，是同样的问题。谢谢

![broken](https://cloud.githubusercontent.com/assets/1848396/24182348/b5742ebe-0e97-11e7-8cd4-eb40494467af.png)

是solver配置的问题，已解决~

**Comment by suhangpro** [comment]
Fixed in #8
